; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
;upload_port = /dev/ttyACM0
lib_deps = 
	mobizt/ESP Mail Client@^3.4.15
	mikalhart/TinyGPSPlus@^1.0.3
	plerup/EspSoftwareSerial@8.1.0
	adafruit/Adafruit RGB LCD Shield Library@^1.2.2
	D:\estudis\2023_2024\GEE+GEEIA_5\tfg_urv\documents_lab243\llibreries_arduino\arduino-LoRa-master.zip
	knolleary/PubSubClient@^2.8
